title: Wrapper Offline Electron
logo: /assets/img/logo.png
description: Wrapper Offline Electron Official Website for users
show_downloads: true
google_analytics:
theme: jekyll-theme-midnight
github:
  zip_url: data:text/html;charset=utf-8,<script>alert('No Download yet')</script>
  tar_url: data:text/html;charset=utf-8,<script>alert('No Download yet')</script>
