title: Wrapper Offline Electron
logo: /assets/img/logo.png
description: Wrapper Offline Electron Official Website for users
show_downloads: true
google_analytics:
theme: jekyll-theme-midnight
github:
  zip_url: javascript:alert('Please go to the downloads section to download the one based on your OS')
  tar_url: javascript:alert('Please go to the downloads section to download the one based on your OS')
