title: Wrapper Offline Electron
logo: /assets/img/logo.png
description: Wrapper Offline Electron Official Website for users
show_downloads: true
google_analytics:
theme: jekyll-theme-midnight
github:
  zip_url: data:text/html;charset=utf-8,<p>There is no ZIP available currently, please use Universal Installer to install Wrapper Offline Electron</p>
  another_url: data:text/html;charset=utf-8,<p>Test</p>
